### ISSUE TITLE
data/pdf_previews plot dose not match Instructions.pdf model

### ISSUE THREAD

**Issue by yugo-kato** [gprMax/iwagpr2017-model#1]
Plot range in data/pdf_previews plot  (commit 40b1bf1b53f5e736c8791e6aa77b3f4b93959e32)  is seem wrong because it show scan range is from 0.1m to 0.9m. The total scan width of it is 0.8m.
Instructions.pdf model show that scan width is 0.9m (for example, x coordinate change from  0.15m to 1.05m).

Correction of the distance width is necessary.
![xdir_008](https://user-images.githubusercontent.com/849096/26976945-0cd9d6f6-4d61-11e7-8b80-b61af6c2ddd7.png)
The error of the distance width affects estimation of the buried object position and dielectric constant.
![markplot](https://user-images.githubusercontent.com/849096/26976959-186dddf0-4d61-11e7-90a8-77b296955b59.png)
![depth_movie](https://user-images.githubusercontent.com/849096/26976967-22d679c8-4d61-11e7-923a-a2cf141327fa.gif)

**Comment by craig-warren** [comment]
@yugo-kato thanks for spotting the error with the distance on the PDF previews. Now corrected.

If you can tell us a bit more about the processing steps you have taken, we can show your results at IWAGPR2017.

Thanks,

Craig
