### ISSUE TITLE
temporal resolution

### ISSUE THREAD

**Issue by VOKovalenko** [gprMax/iwagpr2017-model#2]
Dear Challenge Masters,

I am confused about the temporal resolution, which is listed as 3.852 ps. I do not come to 8 ns in 2048 samples with it. Should it not be 3.90625ps or is there a t0 of 0.11ns that i miss?

**Comment by craig-warren** [comment]
@VOKovalenko because this is synthetic data we are not restricted to sampling in powers of 2. The number of samples (or iterations in this case) is 2078.

**Comment by VOKovalenko** [comment]
Ah, yes. Thank you.
